[build]
  publish = "dist/"
  command = "./deploy.sh"

[[headers]]
  for = "/images/*"
  [headers.values]
    # Cache images for a week
    cache-control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache scripts for a year
    cache-control = "public, max-age=31536000"
